### ISSUE TITLE
Database Structure

### ISSUE THREAD

**Issue by jagadyudha** [sycwell/citizen#2]
## Description

temporary database structure 

![image](https://user-images.githubusercontent.com/41937681/144741410-28c07078-0753-4612-862e-be09576a88d3.png)

## Task

- [x] The ```endpoint/users/:user_id``` is the only way to get a users data
- [x] Add badge fields to database
- [x] remove field counter and change with field recruitment
- [ ] Make auto increment with value start from 10001 (users)

**Comment by jagadyudha** [comment]
Task 1 done.

![image](https://user-images.githubusercontent.com/41937681/144812991-79546769-6c93-4742-8b42-1ce0878c509c.png)

**Comment by jagadyudha** [comment]
I close this issues, cause doesn't need increment with value start from 10001 anymore.
